server:
  port: 7003
eureka:
  instance:
# eureka服务器名字
    hostname: eureka7003.com
  client:
    # 是否向Eureka注册中心注册自己（这个模块本身是服务器，所以不需要）
    register-with-eureka: false
    # fetch-registry如果是false，表示自己是注册中心，客户端为true
    fetch-registry: false
    # Eureka监控页面~
    service-url:
      #重写Eureka的默认端口以及访问路径 --->http://localhost:7001/eureka/
      # 单机： defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）：7001关联7002、7003
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

