server:
  port: 8001
mybatis:
  type-aliases-package: com.kuang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloudd-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?ServerTimezone=GMT
    username: root
    password: root
#服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eurkea/
  instance:
#    修改eurkea上的默认描述信息
    instance-id: springcloud-provider-dept8001
